// Central Florida Events Dataset
const EVENTS_DATA = [
    {
        id: 1,
        name: "Orlando Philharmonic Orchestra - Symphony Under the Stars",
        category: "arts",
        description: "Experience world-class classical music under the open sky at Lake Eola. This outdoor concert features beloved symphonic masterpieces.",
        location: "Lake Eola Park, Orlando",
        date: "2025-11-15",
        time: "evening",
        price: 45,
        priceCategory: "moderate",
        capacity: "large",
        image: "🎻",
        personalityTags: ["I", "N", "F", "J"],
        vibes: ["cultural", "relaxed", "educational"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "low",
        venue: "outdoor",
        duration: "3 hours",
        tags: ["music", "classical", "outdoor", "romantic", "peaceful"]
    },
    {
        id: 2,
        name: "EDC Orlando - Electric Daisy Carnival",
        category: "music",
        description: "Florida's premier electronic music festival featuring top international DJs, immersive art installations, and carnival rides.",
        location: "Tinker Field, Orlando",
        date: "2025-11-22",
        time: "night",
        price: 189,
        priceCategory: "premium",
        capacity: "large",
        image: "🎧",
        personalityTags: ["E", "S", "P"],
        vibes: ["energetic", "social", "adventurous"],
        groupSizes: ["small", "large"],
        interactivity: "high",
        venue: "outdoor",
        duration: "12 hours",
        tags: ["music", "edm", "festival", "dance", "nightlife"]
    },
    {
        id: 3,
        name: "Winter Park Farmers Market",
        category: "community",
        description: "Browse local produce, artisan goods, and handcrafted items while enjoying live music in the heart of charming Winter Park.",
        location: "Winter Park Train Station",
        date: "2025-11-12",
        time: "morning",
        price: 0,
        priceCategory: "free",
        capacity: "large",
        image: "🥬",
        personalityTags: ["E", "S", "F", "P"],
        vibes: ["relaxed", "social", "cultural"],
        groupSizes: ["solo", "couple", "small", "large"],
        interactivity: "medium",
        venue: "outdoor",
        duration: "4 hours",
        tags: ["farmers-market", "local", "food", "community", "family-friendly"]
    },
    {
        id: 4,
        name: "Escape Room Challenge: The Heist",
        category: "education",
        description: "Work together to solve puzzles and escape within 60 minutes. Can you crack the vault and steal the diamond?",
        location: "The Escape Effect, Downtown Orlando",
        date: "2025-11-16",
        time: "afternoon",
        price: 32,
        priceCategory: "moderate",
        capacity: "small",
        image: "🔐",
        personalityTags: ["E", "N", "T", "J"],
        vibes: ["competitive", "energetic", "creative"],
        groupSizes: ["small"],
        interactivity: "high",
        venue: "indoor",
        duration: "1 hour",
        tags: ["puzzle", "teamwork", "adventure", "challenge", "interactive"]
    },
    {
        id: 5,
        name: "Meditation & Mindfulness Workshop",
        category: "education",
        description: "Learn practical meditation techniques and mindfulness practices to reduce stress and find inner peace.",
        location: "Yoga Sanctuary, Altamonte Springs",
        date: "2025-11-13",
        time: "morning",
        price: 15,
        priceCategory: "budget",
        capacity: "small",
        image: "🧘‍♀️",
        personalityTags: ["I", "N", "F", "P"],
        vibes: ["relaxed", "educational", "cultural"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "low",
        venue: "indoor",
        duration: "2 hours",
        tags: ["wellness", "meditation", "mindfulness", "health", "peaceful"]
    },
    {
        id: 6,
        name: "Food Truck Rally at Baldwin Park",
        category: "food",
        description: "Sample cuisine from 20+ food trucks offering everything from tacos to artisan ice cream. Live music and family activities.",
        location: "Baldwin Park, Orlando",
        date: "2025-11-17",
        time: "evening",
        price: 0,
        priceCategory: "free",
        capacity: "large",
        image: "🌮",
        personalityTags: ["E", "S", "F", "P"],
        vibes: ["social", "relaxed", "energetic"],
        groupSizes: ["couple", "small", "large"],
        interactivity: "medium",
        venue: "outdoor",
        duration: "4 hours",
        tags: ["food", "family-friendly", "music", "community", "casual"]
    },
    {
        id: 7,
        name: "Orlando Magic vs Miami Heat",
        category: "sports",
        description: "Catch the rivalry game as the Magic take on the Heat in an electrifying NBA matchup at the Kia Center.",
        location: "Kia Center, Orlando",
        date: "2025-11-19",
        time: "night",
        price: 85,
        priceCategory: "premium",
        capacity: "large",
        image: "🏀",
        personalityTags: ["E", "S", "T", "P"],
        vibes: ["energetic", "competitive", "social"],
        groupSizes: ["couple", "small", "large"],
        interactivity: "low",
        venue: "indoor",
        duration: "3 hours",
        tags: ["basketball", "sports", "nba", "entertainment", "exciting"]
    },
    {
        id: 8,
        name: "Art After Dark: Contemporary Exhibition Opening",
        category: "arts",
        description: "Exclusive evening gallery opening featuring emerging local artists. Wine, light bites, and artist meet-and-greet included.",
        location: "CityArts Factory, Orlando",
        date: "2025-11-14",
        time: "evening",
        price: 25,
        priceCategory: "moderate",
        capacity: "medium",
        image: "🎨",
        personalityTags: ["I", "N", "F", "P"],
        vibes: ["creative", "cultural", "social", "relaxed"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "medium",
        venue: "indoor",
        duration: "3 hours",
        tags: ["art", "gallery", "wine", "networking", "culture"]
    },
    {
        id: 9,
        name: "Kayaking Eco-Tour: Wekiwa Springs",
        category: "outdoor",
        description: "Paddle through crystal-clear springs and natural wildlife habitats. Guided tour includes equipment and naturalist insights.",
        location: "Wekiwa Springs State Park",
        date: "2025-11-18",
        time: "morning",
        price: 55,
        priceCategory: "moderate",
        capacity: "small",
        image: "🛶",
        personalityTags: ["I", "S", "T", "P"],
        vibes: ["adventurous", "relaxed", "educational"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "high",
        venue: "outdoor",
        duration: "3 hours",
        tags: ["kayaking", "nature", "wildlife", "outdoor", "adventure"]
    },
    {
        id: 10,
        name: "Stand-Up Comedy Night",
        category: "arts",
        description: "Laugh out loud with a lineup of hilarious comedians at Orlando's premier comedy club. Full bar and food menu available.",
        location: "SAK Comedy Lab, Downtown Orlando",
        date: "2025-11-20",
        time: "night",
        price: 18,
        priceCategory: "budget",
        capacity: "medium",
        image: "😂",
        personalityTags: ["E", "N", "F", "P"],
        vibes: ["energetic", "social", "relaxed"],
        groupSizes: ["couple", "small", "large"],
        interactivity: "low",
        venue: "indoor",
        duration: "2 hours",
        tags: ["comedy", "entertainment", "nightlife", "laughter", "date-night"]
    },
    {
        id: 11,
        name: "Vintage Market Pop-Up",
        category: "community",
        description: "Shop curated vintage clothing, records, home decor, and antiques from local collectors and vendors.",
        location: "The Venue, Sanford",
        date: "2025-11-23",
        time: "afternoon",
        price: 5,
        priceCategory: "budget",
        capacity: "medium",
        image: "🛍️",
        personalityTags: ["I", "S", "F", "P"],
        vibes: ["creative", "relaxed", "cultural"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "medium",
        venue: "indoor",
        duration: "4 hours",
        tags: ["shopping", "vintage", "antiques", "local", "unique"]
    },
    {
        id: 12,
        name: "Trivia Championship Night",
        category: "education",
        description: "Test your knowledge across pop culture, history, science, and sports. Cash prizes for winning teams!",
        location: "Sportstown Billiards, Orlando",
        date: "2025-11-21",
        time: "night",
        price: 0,
        priceCategory: "free",
        capacity: "large",
        image: "🧠",
        personalityTags: ["E", "N", "T", "J"],
        vibes: ["competitive", "social", "educational"],
        groupSizes: ["small", "large"],
        interactivity: "high",
        venue: "indoor",
        duration: "2.5 hours",
        tags: ["trivia", "competition", "knowledge", "team", "social"]
    },
    {
        id: 13,
        name: "Sunrise Hot Air Balloon Ride",
        category: "outdoor",
        description: "Float peacefully over Central Florida landscapes at dawn. Includes champagne toast and breakfast after landing.",
        location: "Launch sites near Kissimmee",
        date: "2025-11-24",
        time: "morning",
        price: 225,
        priceCategory: "premium",
        capacity: "small",
        image: "🎈",
        personalityTags: ["I", "N", "F", "J"],
        vibes: ["adventurous", "relaxed", "romantic"],
        groupSizes: ["couple", "small"],
        interactivity: "low",
        venue: "outdoor",
        duration: "3 hours",
        tags: ["hot-air-balloon", "romantic", "scenic", "unique", "peaceful"]
    },
    {
        id: 14,
        name: "5K Color Run for Charity",
        category: "sports",
        description: "Fun run where participants get doused in colored powder at each kilometer. All proceeds benefit local children's hospital.",
        location: "Cranes Roost Park, Altamonte Springs",
        date: "2025-11-25",
        time: "morning",
        price: 35,
        priceCategory: "moderate",
        capacity: "large",
        image: "🏃",
        personalityTags: ["E", "S", "F", "P"],
        vibes: ["energetic", "social", "adventurous"],
        groupSizes: ["solo", "couple", "small", "large"],
        interactivity: "high",
        venue: "outdoor",
        duration: "2 hours",
        tags: ["running", "fitness", "charity", "fun", "community"]
    },
    {
        id: 15,
        name: "Cooking Class: Italian Cuisine Masterclass",
        category: "food",
        description: "Learn to make authentic pasta from scratch, plus classic sauces and tiramisu. Enjoy your creations with wine pairings.",
        location: "Sur La Table, Winter Park Village",
        date: "2025-11-26",
        time: "evening",
        price: 89,
        priceCategory: "premium",
        capacity: "small",
        image: "👨‍🍳",
        personalityTags: ["I", "S", "T", "J"],
        vibes: ["educational", "creative", "social"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "high",
        venue: "indoor",
        duration: "3 hours",
        tags: ["cooking", "food", "italian", "class", "wine"]
    },
    {
        id: 16,
        name: "Jazz Night at The Social",
        category: "music",
        description: "Intimate evening of smooth jazz featuring local musicians. Full bar, relaxed atmosphere, and great acoustics.",
        location: "The Social, Downtown Orlando",
        date: "2025-11-27",
        time: "night",
        price: 15,
        priceCategory: "budget",
        capacity: "medium",
        image: "🎷",
        personalityTags: ["I", "N", "F", "P"],
        vibes: ["relaxed", "cultural", "creative"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "low",
        venue: "indoor",
        duration: "3 hours",
        tags: ["jazz", "music", "nightlife", "intimate", "sophisticated"]
    },
    {
        id: 17,
        name: "Virtual Reality Gaming Tournament",
        category: "sports",
        description: "Compete in cutting-edge VR games. All skill levels welcome. Top prizes and bragging rights await!",
        location: "Ctrl V Virtual Reality Arcade, Orlando",
        date: "2025-11-28",
        time: "afternoon",
        price: 40,
        priceCategory: "moderate",
        capacity: "medium",
        image: "🥽",
        personalityTags: ["E", "S", "T", "P"],
        vibes: ["competitive", "energetic", "adventurous"],
        groupSizes: ["solo", "small"],
        interactivity: "high",
        venue: "indoor",
        duration: "2 hours",
        tags: ["gaming", "vr", "technology", "competition", "modern"]
    },
    {
        id: 18,
        name: "Botanical Gardens Sunset Tour",
        category: "outdoor",
        description: "Guided walking tour through themed gardens at golden hour. Learn about rare plants and sustainable gardening practices.",
        location: "Harry P. Leu Gardens, Orlando",
        date: "2025-11-29",
        time: "evening",
        price: 12,
        priceCategory: "budget",
        capacity: "small",
        image: "🌺",
        personalityTags: ["I", "S", "F", "J"],
        vibes: ["relaxed", "educational", "cultural"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "low",
        venue: "outdoor",
        duration: "1.5 hours",
        tags: ["gardens", "nature", "peaceful", "educational", "photography"]
    },
    {
        id: 19,
        name: "Craft Beer & Board Games Night",
        category: "community",
        description: "Play from our library of 200+ board games while sampling local craft beers. Game experts available to teach.",
        location: "Cloak & Blaster, Orlando",
        date: "2025-11-30",
        time: "evening",
        price: 8,
        priceCategory: "budget",
        capacity: "medium",
        image: "🎲",
        personalityTags: ["E", "N", "T", "P"],
        vibes: ["social", "relaxed", "creative"],
        groupSizes: ["couple", "small", "large"],
        interactivity: "high",
        venue: "indoor",
        duration: "3 hours",
        tags: ["board-games", "beer", "social", "strategy", "casual"]
    },
    {
        id: 20,
        name: "Stargazing at the Observatory",
        category: "education",
        description: "Use professional telescopes to observe planets, nebulae, and distant galaxies. Astronomy experts provide commentary.",
        location: "Robinson Observatory, Lake Wales",
        date: "2025-12-01",
        time: "night",
        price: 10,
        priceCategory: "budget",
        capacity: "small",
        image: "🔭",
        personalityTags: ["I", "N", "T", "J"],
        vibes: ["educational", "relaxed", "adventurous"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "medium",
        venue: "outdoor",
        duration: "2 hours",
        tags: ["astronomy", "science", "stargazing", "educational", "unique"]
    },
    {
        id: 21,
        name: "Latin Dance Social - Salsa & Bachata",
        category: "arts",
        description: "Beginner lesson followed by open social dancing. No partner required - we rotate! All skill levels welcome.",
        location: "Orlando Salsa & Bachata, International Drive",
        date: "2025-12-02",
        time: "evening",
        price: 12,
        priceCategory: "budget",
        capacity: "large",
        image: "💃",
        personalityTags: ["E", "S", "F", "P"],
        vibes: ["energetic", "social", "creative"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "high",
        venue: "indoor",
        duration: "3 hours",
        tags: ["dancing", "salsa", "social", "fitness", "latin"]
    },
    {
        id: 22,
        name: "Poetry Open Mic Night",
        category: "arts",
        description: "Share your original poetry or simply listen to local spoken word artists. Supportive, creative community atmosphere.",
        location: "Stardust Coffee & Video, Orlando",
        date: "2025-12-03",
        time: "night",
        price: 0,
        priceCategory: "free",
        capacity: "small",
        image: "📝",
        personalityTags: ["I", "N", "F", "P"],
        vibes: ["creative", "cultural", "relaxed"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "medium",
        venue: "indoor",
        duration: "2 hours",
        tags: ["poetry", "open-mic", "art", "creative", "coffee"]
    },
    {
        id: 23,
        name: "Mountain Bike Trail Adventure",
        category: "sports",
        description: "Guided ride through challenging forest trails. Bike rentals available. All fitness levels with multiple route options.",
        location: "Little Big Econ State Forest",
        date: "2025-12-04",
        time: "morning",
        price: 30,
        priceCategory: "moderate",
        capacity: "small",
        image: "🚵",
        personalityTags: ["E", "S", "T", "P"],
        vibes: ["adventurous", "energetic", "competitive"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "high",
        venue: "outdoor",
        duration: "3 hours",
        tags: ["biking", "outdoor", "fitness", "adventure", "nature"]
    },
    {
        id: 24,
        name: "Wine & Painting Workshop",
        category: "arts",
        description: "No experience needed! Follow along to create your own masterpiece while enjoying wine. All supplies included.",
        location: "Pinot's Palette, Winter Park",
        date: "2025-12-05",
        time: "evening",
        price: 45,
        priceCategory: "moderate",
        capacity: "medium",
        image: "🍷",
        personalityTags: ["I", "S", "F", "P"],
        vibes: ["creative", "relaxed", "social"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "high",
        venue: "indoor",
        duration: "2 hours",
        tags: ["painting", "wine", "art", "creative", "social"]
    },
    {
        id: 25,
        name: "Tech Startup Pitch Competition",
        category: "education",
        description: "Watch innovative startups pitch their ideas to investors. Networking reception follows. Great for entrepreneurs!",
        location: "Canvs Coworking, Downtown Orlando",
        date: "2025-12-06",
        time: "evening",
        price: 0,
        priceCategory: "free",
        capacity: "medium",
        image: "💼",
        personalityTags: ["E", "N", "T", "J"],
        vibes: ["educational", "competitive", "social"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "medium",
        venue: "indoor",
        duration: "2.5 hours",
        tags: ["tech", "startup", "business", "networking", "innovation"]
    },
    {
        id: 26,
        name: "Moonlight Paddleboard Yoga",
        category: "outdoor",
        description: "Practice yoga on paddleboards under the stars. Magical experience combining fitness, nature, and mindfulness.",
        location: "Lake Baldwin, Orlando",
        date: "2025-12-07",
        time: "night",
        price: 40,
        priceCategory: "moderate",
        capacity: "small",
        image: "🧘",
        personalityTags: ["I", "N", "F", "P"],
        vibes: ["relaxed", "adventurous", "creative"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "high",
        venue: "outdoor",
        duration: "1.5 hours",
        tags: ["yoga", "paddleboard", "wellness", "unique", "peaceful"]
    },
    {
        id: 27,
        name: "Street Food Festival",
        category: "food",
        description: "Taste global cuisines from 30+ vendors. Live cooking demos, eating contests, and cultural performances.",
        location: "Festival Park at Lake Nona",
        date: "2025-12-08",
        time: "afternoon",
        price: 0,
        priceCategory: "free",
        capacity: "large",
        image: "🍜",
        personalityTags: ["E", "S", "F", "P"],
        vibes: ["energetic", "social", "cultural"],
        groupSizes: ["couple", "small", "large"],
        interactivity: "medium",
        venue: "outdoor",
        duration: "5 hours",
        tags: ["food", "international", "festival", "family-friendly", "cultural"]
    },
    {
        id: 28,
        name: "Mystery Dinner Theater",
        category: "arts",
        description: "Interactive murder mystery where you're part of the story. Four-course dinner included. Solve the crime!",
        location: "Sleuth's Mystery Dinner Shows, I-Drive",
        date: "2025-12-09",
        time: "evening",
        price: 65,
        priceCategory: "premium",
        capacity: "large",
        image: "🕵️",
        personalityTags: ["E", "N", "F", "J"],
        vibes: ["creative", "social", "energetic"],
        groupSizes: ["couple", "small", "large"],
        interactivity: "high",
        venue: "indoor",
        duration: "3 hours",
        tags: ["theater", "dinner", "mystery", "interactive", "entertainment"]
    },
    {
        id: 29,
        name: "Photography Walk: Historic Downtown",
        category: "arts",
        description: "Guided photo walk through Orlando's historic architecture. Tips on composition and lighting. All camera types welcome.",
        location: "Downtown Orlando Historic District",
        date: "2025-12-10",
        time: "morning",
        price: 20,
        priceCategory: "budget",
        capacity: "small",
        image: "📸",
        personalityTags: ["I", "S", "T", "P"],
        vibes: ["creative", "educational", "relaxed"],
        groupSizes: ["solo", "couple", "small"],
        interactivity: "medium",
        venue: "outdoor",
        duration: "2 hours",
        tags: ["photography", "art", "walking", "historic", "educational"]
    },
    {
        id: 30,
        name: "Improv Comedy Workshop",
        category: "education",
        description: "Learn improv basics and have fun with games and exercises. Great for building confidence and meeting people!",
        location: "SAK Comedy Lab, Downtown Orlando",
        date: "2025-12-11",
        time: "evening",
        price: 35,
        priceCategory: "moderate",
        capacity: "small",
        image: "🎭",
        personalityTags: ["E", "N", "F", "P"],
        vibes: ["creative", "social", "energetic"],
        groupSizes: ["solo", "small"],
        interactivity: "high",
        venue: "indoor",
        duration: "2 hours",
        tags: ["improv", "comedy", "workshop", "social", "creativity"]
    }
];
